# Generated by Django 2.1.3 on 2018-11-23 06:09

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=55)),
                ('slug', models.SlugField(max_length=55)),
                ('is_company', models.BooleanField(default=False)),
                ('is_independent', models.BooleanField(default=False)),
                ('about', models.TextField()),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('line_id', models.CharField(blank=True, max_length=25, unique=True)),
                ('logo', models.ImageField(default='logos/default.jpeg', upload_to=accounts.models.user_directory_path)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContentManager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=125)),
                ('last_name', models.CharField(max_length=125)),
                ('bio', models.TextField(max_length=255)),
                ('avatar', models.ImageField(default='https://api.adorable.io/avatars/285/abott@adorable.png', upload_to=accounts.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='VerificicationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('document', models.FileField(upload_to='documents')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
