# Generated by Django 2.1.3 on 2018-11-23 06:09

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('slug', models.SlugField()),
                ('subtitle', models.CharField(blank=True, max_length=122)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to=blog.models.user_directory_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
